name: portfolio
description: Xavier C. portfolio.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^5.7.4
  provider: ^4.3.2+3
  get_it: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^1.6.2
  mockito: ^4.1.1
  lint: ^1.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: fonts/JetBrainsMono/JetBrainsMono-ExtraBold-Italic.ttf
          weight: 800
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono/JetBrainsMono-Bold-Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: fonts/JetBrainsMono/JetBrainsMono-Medium-Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: fonts/JetBrainsMono/JetBrainsMono-Italic.ttf
          weight: 400
          style: italic
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: AppIntl
