name: Build and release to Github pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
      - name: Get packages from pub
        run: flutter pub get
      - name: Build web app
        run: flutter build web --web-renderer html
      - name: Publish to Github pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        with:
          email: chretienxavier42@gmail.com
          build_dir: ./build/web
          cname: xavierc.dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
