name: Build and release to Github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.24.x'
          channel: 'beta'
      - name: Get packages from pub
        run: flutter pub get
      - name: Generate l10n classes
        run: flutter pub run intl_utils:generate
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: Build web app
        run: flutter build web
      - name: Publish to Github pages
        uses: Cecilapp/GitHub-Pages-deploy@2.0.1
        env:
          EMAIL: chretienxavier42@gmail.com
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: ./build/web
          CNAME: xavierc.dev
